name: publish-with-yarn-classic
description: Publishes a NPM package using Yarn Classic
branding:
  icon: upload-cloud
  color: green

inputs:
  npm-auth-token:
    description: "NPM token"
    required: true

runs:
  using: composite
  steps:
    - name: Get version from git tag 🏷️
      id: version
      uses: jannemattila/get-version-from-tag@v3

    - name: Set version to release tag 📝
      shell: bash
      run: yarn version --no-commit-hooks --no-git-tag-version --new-version ${{
        steps.version.outputs.version }}

    - name: Publish 🚀
      shell: bash
      run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-auth-token }}

    - name: Push version changes to main branch 📤
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: release ${{ github.event.release.tag_name }}"
        branch: ${{ github.event.repository.default_branch }}
        file_pattern: package.json
